# Site settings
title: Posts by KygekDev
description: Posts by KygekDev
url: https://kygekdev.github.io

# Build settings
baseurl: /posts # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page-:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-multiple-languages-plugin
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-multiple-languages-plugin

# Custom variables
version: "1.0.0"
languages: ["en", "id", "fr", "es", "ru", "tr", "zh", "ko", "ja"]
exclude_from_localizations: ["javascript", "images", "css"]

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# Analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-179045405-5
    anonymizeIp: true   # Privacy
